server.port=8080

# URLs de las funciones Serverless de Azure
faas.usuarios.url=https://faas-biblioteca-haim2026-bpegchbnb5a3fpaq.brazilsouth-01.azurewebsites.net/api/usuarios
faas.prestamos.url=https://faas-biblioteca-haim2026-bpegchbnb5a3fpaq.brazilsouth-01.azurewebsites.net/api/prestamos